image: registry.freedesktop.org/pipewire/pipewire/fedora:31

build:
  stage: build
  script:
     - ./autogen.sh -Ddocs=true -Daudiomixer=true -Daudiotestsrc=true -Dtest=true -Dvideotestsrc=true -Dvolume=true
     - make
     - make test
     - DESTDIR=$PWD/build/i make install
     - PREFIX=$PWD/build/i/usr/local ./check_missing_headers.sh
  artifacts:
    paths:
      - build/
